from __future__ import annotations

import os
from pathlib import Path
from typing import Literal

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError

_STRICT = ConfigDict(extra="forbid")

PolicyMode = Literal["auto", "confirm", "dry-run", "deny"]
LogLevel = Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]


class DefaultsConfig(BaseModel):
    model_config = _STRICT

    model: str = "gemini-2.5-flash"
    max_turns: int = Field(default=40, gt=0)
    wall_clock_s: float = Field(default=600.0, gt=0)
    runs_dir: str = "./runs"
    logs_dir: str = "./logs"
    device_serial: str | None = None


class ProvidersConfig(BaseModel):
    """Placeholder — fleshed out in milestone 2 (LiteLLM provider seam)."""
    model_config = _STRICT


class ThrottlerConfig(BaseModel):
    """Placeholder — fleshed out in milestone 3 (token bucket + Router)."""
    model_config = _STRICT

    enabled: bool = False
    buckets: dict[str, dict] = Field(default_factory=dict)


class PolicyConfig(BaseModel):
    """Placeholder — fleshed out in milestone 4 (destructive-action gating)."""
    model_config = _STRICT

    default_mode: PolicyMode = "auto"
    per_tool: dict[str, PolicyMode] = Field(default_factory=dict)


class MemoryConfig(BaseModel):
    """Placeholder — fleshed out in milestone 12 (chromadb episodic memory)."""
    model_config = _STRICT

    enabled: bool = False
    embedding_model: str = "gemini-text-embedding-004"
    retention_days: int = Field(default=60, gt=0)


class PerceptionConfig(BaseModel):
    """Placeholder — toggles flip on as milestones 6, 11, 16 land."""
    model_config = _STRICT

    sibling_collapse: bool = False
    viewport_filter: bool = False
    resource_id_in_render: bool = False
    screenshot_quantized: bool = False


class LoggingConfig(BaseModel):
    model_config = _STRICT

    level: LogLevel = "INFO"
    rotation_mb: int = Field(default=10, gt=0)


class AndroidHarnessConfig(BaseModel):
    model_config = _STRICT

    version: Literal[1] = 1
    defaults: DefaultsConfig = Field(default_factory=DefaultsConfig)
    providers: ProvidersConfig = Field(default_factory=ProvidersConfig)
    throttler: ThrottlerConfig = Field(default_factory=ThrottlerConfig)
    policy: PolicyConfig = Field(default_factory=PolicyConfig)
    memory: MemoryConfig = Field(default_factory=MemoryConfig)
    perception: PerceptionConfig = Field(default_factory=PerceptionConfig)
    logging: LoggingConfig = Field(default_factory=LoggingConfig)


CONFIG_HEADER = (
    "# AndroidHarness config — see docs/superpowers/specs/2026-05-20-v2-stack-and-scale-design.md\n"
    "# Generated by `androidharness config init`. Edit by hand or via the Settings UI (v2.0).\n"
    "---\n"
)


class ConfigError(RuntimeError):
    """Raised when a config file is malformed or fails schema validation."""


def default_config_path() -> Path:
    """Resolve the config path, honoring the `ANDROIDHARNESS_CONFIG` env var override."""
    override = os.environ.get("ANDROIDHARNESS_CONFIG")
    if override:
        return Path(override).expanduser()
    return Path(os.environ.get("HOME", "~")).expanduser() / ".androidharness" / "config.yaml"


def load_config(path: Path | None = None) -> AndroidHarnessConfig:
    """Load config from disk. Missing file → defaults. Malformed → ConfigError."""
    p = Path(path) if path is not None else default_config_path()
    if not p.exists():
        return AndroidHarnessConfig()
    try:
        raw = yaml.safe_load(p.read_text()) or {}
    except yaml.YAMLError as e:
        raise ConfigError(f"failed to parse YAML in {p}: {e}") from e
    if not isinstance(raw, dict):
        raise ConfigError(f"config at {p} must be a YAML mapping at the top level")
    try:
        return AndroidHarnessConfig.model_validate(raw)
    except ValidationError as e:
        raise ConfigError(f"config at {p} failed validation:\n{e}") from e


def save_config(config: AndroidHarnessConfig, path: Path | None = None) -> Path:
    """Serialize config to YAML with a header comment. Creates parent dirs."""
    p = Path(path) if path is not None else default_config_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        config.model_dump(mode="json"),
        sort_keys=False,
        default_flow_style=False,
    )
    p.write_text(CONFIG_HEADER + body)
    return p
